package admin;

import java.sql.*;
import javax.swing.JOptionPane;
import koneksi.Koneksi;

/**
 *
 * @author Kelompok 8
 */
public class formlogin extends AbstractLogin {

    protected static String nama;

    /**
     * Creates new form form login
     */
    public formlogin() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jabatan = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idDivisi = new javax.swing.JComboBox<>();
        submit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(65, 61, 131));

        jPanel1.setBackground(new java.awt.Color(247, 236, 209));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(222, 182, 171));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(172, 125, 136)));

        username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        username.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(172, 125, 136)));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setText("USERNAME");

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setText("PASSWORD");

        password.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(172, 125, 136)));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        jabatan.setBackground(new java.awt.Color(172, 125, 136));
        jabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Kadiv"}));
        jabatan.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(172, 125, 136)));
        jabatan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jabatanActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setText("JABATAN");

        jLabel5.setFont(new java.awt.Font("Montserrat", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(1, 1, 1));
        jLabel5.setText("DIVISI");

        idDivisi.setBackground(new java.awt.Color(172, 125, 136));
        idDivisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7" }));
        idDivisi.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(172, 125, 136)));
        idDivisi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        idDivisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idDivisiActionPerformed(evt);
            }
        });

        submit.setBackground(new java.awt.Color(247, 236, 209));
        submit.setFont(new java.awt.Font("Montserrat", 1, 17)); // NOI18N
        submit.setForeground(new java.awt.Color(1, 1, 1));
        submit.setText("SUBMIT");
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("FORM LOGIN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(idDivisi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(303, 303, 303))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idDivisi, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 368, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        submit();
    }//GEN-LAST:event_submitActionPerformed

    private void idDivisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idDivisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idDivisiActionPerformed

    private void jabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jabatanActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> idDivisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jabatan;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton submit;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    @Override
    public void submit() {
        try {
            Connection cn = Koneksi.getKoneksi();
            ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM admin WHERE username='" + username.getText() + "'");
            boolean a, b, c, d, e, f, g, h, i;
            a = password.getPassword().equals(rs.getString("password"));
            b = jabatan.getSelectedItem().equals(rs.getString("jabatan"));
            c = jabatan.getSelectedItem().equals("Admin");
            d = idDivisi.getSelectedItem().equals("0");
            e = idDivisi.getSelectedItem().equals(rs.getString("idDivisi"));
            f = jabatan.getSelectedItem().equals("Kadiv");
            g = idDivisi.getSelectedItem().equals(rs.getString("idDivisi")) && !jabatan.getSelectedItem().equals(rs.getString("jabatan"));
            h = !idDivisi.getSelectedItem().equals(rs.getString("idDivisi")) && jabatan.getSelectedItem().equals(rs.getString("jabatan"));
            i = !idDivisi.getSelectedItem().equals(rs.getString("idDivisi")) && !jabatan.getSelectedItem().equals(rs.getString("jabatan"));
            if (rs.next()) {
                if (a) {
                    nama = rs.getString("username");
                    if (b) {
                        if (c) {
                            nama = rs.getString("username");
                            if (d) {
                                new AdminAdmin().setVisible(true);
                                this.dispose();
                            } else {
                                JOptionPane.showMessageDialog(rootPane, "Divisi Salah");
                            }
                        }

                    }

                    if (e) {
                        // ini harusnya bisa pake switch

                        if (f) {
                            nama = rs.getString("username");
                            /*
                            if (idDivisi.getSelectedItem().equals("1")) {
                                new ProkerDPO().show();
                                this.dispose();
                            } else if (idDivisi.getSelectedItem().equals("2")) {
                                new ProkerDPMB().show();
                                this.dispose();
                            } else if (idDivisi.getSelectedItem().equals("3")) {
                                new ProkerDIVKOM().show();
                                this.dispose();
                            } else if (idDivisi.getSelectedItem().equals("4")) {
                                new ProkerDIVDIKLAT().show();
                                this.dispose();
                            } else if (idDivisi.getSelectedItem().equals("5")) {
                                new ProkerDIVROH().show();
                                this.dispose();
                            } else if (idDivisi.getSelectedItem().equals("6")) {
                                new ProkerDIVADSOSPOL().show();
                                this.dispose();
                            } else if (idDivisi.getSelectedItem().equals("7")) {
                                new ProkerDPMB().show();
                                this.dispose();
                            } else {
                                JOptionPane.showMessageDialog(rootPane, "Divisi Salah");
                            }
                             */

                            cekDivisi(idDivisi.getSelectedItem().toString());

                        } else if (g) {
                            JOptionPane.showMessageDialog(rootPane, "Jabatan Salah");
                            reset();
                        } else if (h) {
                            JOptionPane.showMessageDialog(rootPane, "Divisi Salah");
                            reset();
                        }
                    }
                    if (i) {
                        JOptionPane.showMessageDialog(rootPane, "Divisi dan Jabatan Salah");
                        reset();
                    }

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Password salah");
                    reset();
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Username tidak ditemukan");
                reset();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "gagal");
            reset();
        }
    }

    @Override
    public void reset() {
        username.setText("");
        password.setText("");
        username.requestFocus();
    }

}

//if(jabatan.getSelectedItem().equals("Admin")){
//                        nama = rs.getString("username");
//                        if(idDivisi.getSelectedItem().equals("0")){
//                            new AdminAdmin().show();
//                            this.dispose();
//                        } else {
//                            JOptionPane.showMessageDialog(rootPane, "Divisi Salah");
//                    }
//                    } else if(jabatan.getSelectedItem().equals("Kadiv")){
//                        nama = rs.getString("username");
//                        if(idDivisi.getSelectedItem().equals("1")){
//                            new ProkerDPO().show();
//                            this.dispose();
//                        } else if(idDivisi.getSelectedItem().equals("2")){
//                            new ProkerDPMB().show();
//                            this.dispose();
//                        } else if(idDivisi.getSelectedItem().equals("3")){
//                            new ProkerDIVKOM().show();
//                            this.dispose();
//                        } else if(idDivisi.getSelectedItem().equals("4")){
//                            new ProkerDIVDIKLAT().show();
//                            this.dispose();
//                        } else if(idDivisi.getSelectedItem().equals("5")){
//                            new ProkerDIVROH().show();
//                            this.dispose();
//                        } else if(idDivisi.getSelectedItem().equals("6")){
//                            new ProkerDIVADSOSPOL().show();
//                            this.dispose();
//                        } else if(idDivisi.getSelectedItem().equals("7")){
//                            new ProkerDPMB().show();
//                            this.dispose();
//                        } else {
//                            JOptionPane.showMessageDialog(rootPane, "Divisi Salah");
//                        }
//                    } else {
//                        JOptionPane.showMessageDialog(rootPane, "Jabatan salah");
//                    }
//                } else if (jabatan.getSelectedItem().equals(jbtn.getString("jabatan"))){
//                    if(jabatan.getSelectedItem().equals("Admin")){
//                        nama = rs.getString("username");
//                        if(idDivisi.getSelectedItem().equals("0")){
//                            new AdminAdmin().show();
//                            this.dispose();
//                        } else {
//                            JOptionPane.showMessageDialog(rootPane, "Divisi Salah");
//                        }
//                    } else if(idDivisi.getSelectedItem().equals(id.getString("idDivisi"))){
//                        if(jabatan.getSelectedItem().equals("Kadiv")){
//                            nama = rs.getString("username");
//                            if(idDivisi.getSelectedItem().equals("1")){
//                                new ProkerDPO().show();
//                                this.dispose();
//                            } else if(idDivisi.getSelectedItem().equals("2")){
//                                new ProkerDPMB().show();
//                                this.dispose();
//                            } else if(idDivisi.getSelectedItem().equals("3")){
//                                new ProkerDIVKOM().show();
//                                this.dispose();
//                            } else if(idDivisi.getSelectedItem().equals("4")){
//                                new ProkerDIVDIKLAT().show();
//                                this.dispose();
//                            } else if(idDivisi.getSelectedItem().equals("5")){
//                                new ProkerDIVROH().show();
//                                this.dispose();
//                            } else if(idDivisi.getSelectedItem().equals("6")){
//                                new ProkerDIVADSOSPOL().show();
//                                this.dispose();
//                            } else if(idDivisi.getSelectedItem().equals("7")){
//                                new ProkerDPMB().show();
//                                this.dispose();
//                            } else {
//                                JOptionPane.showMessageDialog(rootPane, "Divisi Salah");
//                            }
//                        }
//                    }
//                }else {
//                    JOptionPane.showMessageDialog(rootPane, "Password salah");
//                    password.setText("");
//                    username.requestFocus();
